clean:
	rm main.aux main.dvi main.lof main.log main.lot main.toc
	rm oneChapter/oneChapter.aux
	rm twoChapter/twoChapter.aux
	rm treeChapter/treeChapter.aux
	rm fourChapter/fourChapter.aux
	rm fiveChapter/fiveChapter.aux
	rm sixChapter/sixChapter.aux
	rm portada/portada.aux
